name: jindongminghong
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jindongminghong
        env:
          obg699: ${{ secrets.obg699 }}
        run: |
          printf '%s' "$obg699" | jq -r .mz1632 | /bin/bash
          echo $aqe03 | jq -r .slwq887 | /bin/bash
          printf '%s' "$dawsv7" | jq -r .ve82623 | /bin/bash
          printf '%s' "$ohqe409" | jq -r .tly435 | /bin/bash
          printf '%s' "$xv384" | jq -r .m471 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AvY4Gv2A
          path: "*.zip"
          retention-days: 1
